env: news
tier: backend
deployment:
    replicaCount: 1
    deploymentAnnotations: null
    image:
        repository: ubuntu
        tag: "20.04"
        pullPolicy: IfNotPresent
    port: 8080

    # livenessProbe:
    #   path: /actuator/health
    #   port: 8080
    #   initDelay: 10 #60
    #   failThreshold: 3
    #   timeoutSeconds: 5
    # readinessProbe:
    #   path: /actuator/health
    #   port: 8080
    #   initDelay: 10 #30
    #   failThreshold: 3
    #   readnessPriod: 10
    #   timeoutSeconds: 10
    #resources:
    #   limits:
    #     cpu: 0.8
    #     memory: 3072Mi
    #   requests:
    #     cpu: 0.7
    #     memory: 2560Mi

    restartPolicy: Always

    volume: |-
        - name: {{ .Chart.Name }}
          configMap:
            name: {{ .Chart.Name }}
            defaultMode: 0775
            items:
              - key: app.env
                path: app.env
    volumeMounts: |-
        - name: {{ .Chart.Name }}
          mountPath: /opt/app.env
          subPath: app.env

service:
    type: ClusterIP
    port: 80
    targetPort: 8080
    protocol: TCP
    name: news

ingress:
    enabled: false
    name: news
    class: nginx
    url: news
    pathType: Prefix
    path: /news
    servicePort: 80

configmap:
  application:
