env: news
tier: backend
deployment:
    replicaCount: 1
    deploymentAnnotations: null
    image:
        repository: ubuntu
        tag: "22.04"
        pullPolicy: IfNotPresent
    port: 8080
    # livenessProbe:
    #   path: /actuator/health
    #   port: 8080
    #   initDelay: 10 #60
    #   failThreshold: 3
    #   timeoutSeconds: 5
    # readinessProbe:
    #   path: /actuator/health
    #   port: 8080
    #   initDelay: 10 #30
    #   failThreshold: 3
    #   readnessPriod: 10
    #   timeoutSeconds: 10
    #resources:
    #   limits:
    #     cpu: 0.8
    #     memory: 3072Mi
    #   requests:
    #     cpu: 0.7
    #     memory: 2560Mi
    restartPolicy: Always
    volume: |-
        - name: {{ .Chart.Name }}
          configMap:
            name: {{ .Chart.Name }}
            defaultMode: 0775
            items:
              - key: app.env
                path: app.env
    volumeMounts: |-
        - name: {{ .Chart.Name }}
          mountPath: /opt/app.env
          subPath: app.env
service:
    type: ClusterIP
    port: 80
    targetPort: 8080
    protocol: TCP
    name: news
ingress:
    enabled: false
    name: news
    class: nginx
    url: news
    pathType: Prefix
    path: /news
    servicePort: 80
configmap:
    application:
        DB_HOST: localhost
        DB_NAME: postgres
        DB_USERNAME: ENC[AES256_GCM,data:wJxHCwPFITY=,iv:s/ev3eEyDqYvsli1//h72BcEQj92CzQDCzfMmAAuDNg=,tag:a1jcXXF7YLUF6dhA7gIYFA==,type:str]
        DB_PASSWORD: ENC[AES256_GCM,data:sw90lPGXXqTvmXSmtA==,iv:SDhoRuPyEEYcuKTMmcQ4Q82eNY7G5xw+n4DAUwXKpk8=,tag:S9n0RO1FyaYHdDbXZkA25g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v24nznjfxdkt64tsqx677agumnpt7juhjwqgzv0zgatfh4fvlcqqqfm7f8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwQUJIaDZUcURVNGVETnhK
            QzU4M3dnaHhlSlVpNzhNRUFUNjEwMUIrUWhVCnMrWWI1dVBnUXg1VnBSY3ZyUFkw
            a1pzQ1hJOE42TWNxb3FhK1oveGF1QWMKLS0tIG02WDJ0SkNqcU5xV0llRk1jTSth
            eXZZWjhYakZrS0F2VjBHTzRRZlVOVFkKtNpm9d0V7PWG81N4LbGzmG7RnRvKCfGK
            x/+xCWwxAdgkUYvPWBZx2DJ+JFTmiqkHLLz6EpGZBDveJ+2D1y29RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-29T09:26:42Z"
    mac: ENC[AES256_GCM,data:CXsN44Dulb19H1+cK34/BsaPH47eBl0OdVH6lppR/cJBkUxMG3/OjXIW9D8o1NN7Wka+7ZqDEFNzKaVfX60lPnouW4IcWHyLggK9ekJtSkeAl1JQ02Adykb+YLaDnS4J6pSEiVIMuate/D5QEXcQTukydk9nmcDVd7ylr1u1TSk=,iv:aBYjutjbSBAKdjL7D2oTPN7X/e+aizVQD1qw4ShLOlk=,tag:7ije8LB3GCabaGkRfkc+xw==,type:str]
    pgp: []
    encrypted_regex: ^(DB_PASSWORD|DB_USERNAME)$
    version: 3.7.1
