configmap:
    application:
        DB_HOST: localhost
        DB_NAME: postgres
        DB_USERNAME: ENC[AES256_GCM,data:eaWb6HWg/UM=,iv:+hGqoh6b6wJnfCK2AGHZ5QgvBAQz1HGbmQpgxy7hAB8=,tag:JN3dnwYPVgK6LJX1hRIXKw==,type:str]
        DB_PASSWORD: ENC[AES256_GCM,data:KFaVWjuRMF7p+sCk8g==,iv:KDSTb2Qjdtlj2Nv60vUl+tx9SCbtMnMd6+YLZOt1Dv4=,tag:5JjF4v415cCU5bYLKi17zQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v24nznjfxdkt64tsqx677agumnpt7juhjwqgzv0zgatfh4fvlcqqqfm7f8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM2tRb2pTU1VyYVNxc3ZW
            dEJzUnRjQTJSV0FFdHlGMDJ3S3BkMGV5RUdJCjl3UXpzNTN1NnBvQTA3YlJQV0Qv
            UTB2Y2tjVWYrWnVOZjZXdU9XWWpTa1EKLS0tIFU4MmIrT1lOTGVsaWRFdmdhZlp5
            QjNXRVc0QkZPVmJxWlRBYkNlS0F6VVUKGCLOgBOFx0YVaX3V3CX6scBuAEbmd+p/
            R6/B8FuFhGTNaabUStdTSWNXwj3+phUwnq/nRstwoSCkYrQnN3heIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-29T09:44:13Z"
    mac: ENC[AES256_GCM,data:P1C1pgGSpj2qhvYvO7W9eKoZBxpEKJwlTbs1w9w6QX6eYDkBkC1a5XwYYQghu0kCe15IBXqc5KIMgR9GI5Uw1ThQLoBuQWLfYB25QKsZ3FdE+5LN+UxqqNdqEZAJSpFUnmxXXdzxFONSBWU9COBtszQKrAMzfCmnUFaaxDN1Mt8=,iv:ZxUwx6Ni/RubT7vrsAMwhEHeF9w82YuHmGIUDtbZxFg=,tag:lTUXdDd2gncj0f24pLgUhw==,type:str]
    pgp: []
    encrypted_regex: ^(DB_PASSWORD|DB_USERNAME)$
    version: 3.7.1
