env: news
tier: backend
deployment:
    replicaCount: 1
    deploymentAnnotations: null
    image:
        repository: ubuntu
        tag: "22.04"
        pullPolicy: IfNotPresent
    port: 8080
    # livenessProbe:
    #   path: /actuator/health
    #   port: 8080
    #   initDelay: 10 #60
    #   failThreshold: 3
    #   timeoutSeconds: 5
    # readinessProbe:
    #   path: /actuator/health
    #   port: 8080
    #   initDelay: 10 #30
    #   failThreshold: 3
    #   readnessPriod: 10
    #   timeoutSeconds: 10
    #resources:
    #   limits:
    #     cpu: 0.8
    #     memory: 3072Mi
    #   requests:
    #     cpu: 0.7
    #     memory: 2560Mi
    restartPolicy: Always
    volume: |-
        - name: {{ .Chart.Name }}
          configMap:
            name: {{ .Chart.Name }}
            defaultMode: 0775
            items:
              - key: env.app
                path: env.app
    volumeMounts: |-
        - name: {{ .Chart.Name }}
          mountPath: /opt/env.app
          subPath: env.app
service:
    type: ClusterIP
    port: 80
    targetPort: 8080
    protocol: TCP
    name: news
ingress:
    enabled: false
    name: news
    class: nginx
    url: news
    pathType: Prefix
    path: /news
    servicePort: 80
configmap:
    application:
        DB_HOST: localhost
        DB_NAME: postgres
        DB_USERNAME: ENC[AES256_GCM,data:sAzLtZRyO58=,iv:c9/tVbh2JjPgk6Cu8L4dX589A/XV9mqR5Cq1e26Isf0=,tag:WAvaIP3TctIQGZU5DBcklQ==,type:str]
        DB_PASSWORD: ENC[AES256_GCM,data:sUDtLIIQIvJIAxQEow==,iv:OQRzWpcbb+OFO0m7am9Hj/4KGoTbQLv7FUzgiX94p98=,tag:FxBVpNKlMCdTxTWgFARpXw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v24nznjfxdkt64tsqx677agumnpt7juhjwqgzv0zgatfh4fvlcqqqfm7f8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxZjAyektOekpsZENDK1JQ
            NFFSVWhhVWtVa3hyMzRXZ3ZvcUFvN0NIaVdVCkN4UkJrVEdjMVpZZlVDUEtENnVQ
            VVBseU4xRGs4RWQ5NVExcGFkTG56bU0KLS0tIGVtaW9FekhhQkNZK05LalQ5YVgv
            c2xTMXkveHpKR2hZSis2bGJZeUZGZnMKb+8cyzmbQ9F4gqi0kMgvZsYt/vnFg6AW
            CdZdzhlxYvpSzKk49qb93SQm8AReosRAsEbbDyC3JbToLnJyj/u26g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-29T09:30:29Z"
    mac: ENC[AES256_GCM,data:LIo9X1jmjjdPSPkhhIVE9zrNN8krkANnCW+PC24zSWqGEWdurG0s+oic/HMm98GCHH2MkVTMdy2pqwc5Krm21L+QcODGDj+1Qq+nf+/8B/riHd2V89wDbSUXF82745NeeQbWmNEHT+bp7sDtTjsYPXtPEOMyu81r6WJUJPX4t6k=,iv:FTbsdKRWq1kQPHBfwQc88I4SQkkp+AF1UhSq8Mtqqr4=,tag:OI9Jrcf4n6JOisiNAa9vpQ==,type:str]
    pgp: []
    encrypted_regex: ^(DB_PASSWORD|DB_USERNAME)$
    version: 3.7.1
