env: news
tier: backend
deployment:
    replicaCount: 1
    deploymentAnnotations: null
    image:
        repository: ubuntu
        tag: "22.04"
        pullPolicy: IfNotPresent
    port: 8080
    # livenessProbe:
    #   path: /actuator/health
    #   port: 8080
    #   initDelay: 10 #60
    #   failThreshold: 3
    #   timeoutSeconds: 5
    # readinessProbe:
    #   path: /actuator/health
    #   port: 8080
    #   initDelay: 10 #30
    #   failThreshold: 3
    #   readnessPriod: 10
    #   timeoutSeconds: 10
    #resources:
    #   limits:
    #     cpu: 0.8
    #     memory: 3072Mi
    #   requests:
    #     cpu: 0.7
    #     memory: 2560Mi
    restartPolicy: Always
    volume: |-
        - name: {{ .Chart.Name }}
          configMap:
            name: {{ .Chart.Name }}
            defaultMode: 0775
            items:
              - key: app.env
                path: app.env
    volumeMounts: |-
        - name: {{ .Chart.Name }}
          mountPath: /opt/app.env
          subPath: app.env

service:
    type: ClusterIP
    port: 80
    targetPort: 8080
    protocol: TCP
    name: news
    
ingress:
    enabled: false
    name: news
    class: nginx
    url: news
    pathType: Prefix
    path: /news
    servicePort: 80

configmap:
    application:
        NDB_HOST: postgres
        DB_NAME: postgres
        DB_USERNAME: ENC[AES256_GCM,data:/7GuRp8bYb4=,iv:cAB8bSE9zBqx/VP3tJRCmUfehPpAYXUqIVjGdWFwl0s=,tag:tzFeeEIRTh5chGELqkfViA==,type:str]
        DB_PASSWORD: ENC[AES256_GCM,data:nhRao/aw2GYAAK6xD+U=,iv:z1qN91w7WmjkfUOD3nl9lcsE6mRMpG0WPzN7vfA1izg=,tag:c3TkQDmShIcWXiqGZ/H8jw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1v24nznjfxdkt64tsqx677agumnpt7juhjwqgzv0zgatfh4fvlcqqqfm7f8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHSUZCakVCZWZuK1RYcnVt
            NG9Ld2syM25EaUhFd3QyMU0wUC9OV0JLU1FZCjZYeDhQTFRTWWxVRytIOWhzTlc5
            bms3MEcwbmtOTXZIdU0wVmFqM0Q0VUkKLS0tIG1tdmY0MW9pNFhEYTJRL1dnZWd1
            YWEveHRiT0I1MElOVm5OODkyRytMU1kKywp0c9g3IzMAxAMVtmc4Ygy4dfXbPc1w
            yfsQq9zSSk6vOXYwQoF6nBBX3UB3n/eELnW9gDO6pP7k29UzUWYhNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-28T18:12:12Z"
    mac: ENC[AES256_GCM,data:WlUj9vkUY4nPQLgythDM3EU2R/UiP0TzZwbCtiLAVstOeUeJ80/P4uVMCcZQNnjTrQJZprzDAWqFsYzihTYR4IGh+9BMZaHLzQ5hYMvKV31cIakXoO4/3JjgFybVRH7yDgxwGxIaOrY0UtFihz1t25Qkh/DxMBttW+IDktvoCfk=,iv:Qrtohi5b3pTIomvKtPkXOTJO9kS2CSyFZFHsEmOUj+E=,tag:UU6l9rDKIDWYYKeSKxYEdg==,type:str]
    pgp: []
    encrypted_regex: ^(DB_PASSWORD|DB_USERNAME)$
    version: 3.7.1
