apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: helm-project
spec:
  sourceRepos:
    - https://github.com/dyagilev/helm-sops-values.git
  destinations:
    - namespace: test
      server: https://kubernetes.default.svc