apiVersion: v1
kind: Secret
metadata:
  name: github-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/dyagilev/helm-sops-values.git